### ISSUE TITLE
Installation fehlgeschlagen

### ISSUE THREAD

**Issue by BechsteinJ** [hoettges/QKan-plugin-HE7#1]
trotz Installation laut Anleitung meldet Qgis 2.18.24 bei dem Versuch HE-7 über die Erweiterung zu installieren "Diese Erweiterung ist defekt_Metadatendatei fehlt"   Die Metadatendatei ist aber mit in das Verzeichnis kopiert worden.   Die Readme.md ist allerdings auch leer bis auf den Versionsnamen.

![image](https://user-images.githubusercontent.com/46812442/51379672-3a1e4600-1b10-11e9-8e57-207a2e32af06.png)

**Comment by Invisi** [comment]
Moin,
das sieht danach aus, als wäre der falsche Ordner in das Plugin-Verzeichnis kopiert worden.
Lediglich der Ordner `qkan_he7` muss in `...\python\plugins\` abgelegt werden, das ist in der Anleitung leider etwas unglücklich beschrieben.

**Comment by BechsteinJ** [comment]
Vielen Dank!  
nach dem Kopieren des qkan_he7 Ordners in den ...... \qgis-ltr\python\plugins  Ordner ist allerdings das HE7 Plugin gar nicht mehr in dem Erweiterungsrepositorium zu finden.
![image](https://user-images.githubusercontent.com/46812442/51459091-a76fe800-1d57-11e9-973b-010240edc656.png)

![image](https://user-images.githubusercontent.com/46812442/51459118-b9518b00-1d57-11e9-8d0f-725307c30ed0.png)

Sollte es hier nicht zu finden sein?

Besten Dank!

**Comment by Invisi** [comment]
Es müsste zu finden sein, wenn Sie nach `QKan` suchen.  
Der Ordner heißt zwar `qkan_he7`, das Plugin wurde aber `QKan Hystem-Extran 7` genannt.

**Comment by BechsteinJ** [comment]
Na da habe ich mich aber dumm angestellt.

das ist das gute Stück.
Dummerweise stellt jetzt QKAN Hystem -Extran 7 sich immer noch rot da:
![image](https://user-images.githubusercontent.com/46812442/51460788-bf963600-1d5c-11e9-857f-35eafebecced.png)

Konnte Erweiterung qkan_he7 nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

hier die Fehlermeldung:
Exception: The QKan main plugin has to be installed for this extension to work. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\qkan_he7\__init__.py", line 50, in classFactory
    raise Exception('The QKan main plugin has to be installed for this extension to work.')
Exception: The QKan main plugin has to be installed for this extension to work.


Python-Version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.18.24 Las Palmas, ff5bd09ab3 

Python-Pfad:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/jbechstein/.qgis2/python
C:/Users/jbechstein/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/jbechstein/.qgis2//python


die Importschaltflächen für HE-Datenbanken sind auch nicht im QKan Reiter zu finden:
![image](https://user-images.githubusercontent.com/46812442/51460909-01bf7780-1d5d-11e9-9515-0d552e91bab1.png)



Das QKan Plugin ist aber installiert und aktiviert.
Sollte ich hier alles wieder runter werfen und nochmal neu installieren?


Besten Dank für die rasche Antwort!

Beste Grüße
Johannes Bechstein

**Comment by Invisi** [comment]
Hui, das fällt in die Kategorie "Sollte eigentlich nicht passieren".  
Haben Sie mal das Hauptplugin `QKan` deaktiviert, wieder aktiviert, und danach das HE7-Plugin ~~geladen~~ aktiviert?

**Comment by BechsteinJ** [comment]
Jetzt habe ich mal den Ordner qkan_he7 gelöscht und neu ins Verzeichnis kopiert.
Der Fehler bleibt allerdings immer noch der gleiche.

Was wäre hier evtl. das beste vorgehen?  Qgis mal komplett entfernen und neu installieren?

**Comment by Invisi** [comment]
An sich sollte das oben beschriebene reichen. Falls eine komplett Neuinstallation von QKan + QKan HE7 (auch nacheinander aktiviert) auch nicht ausreicht, setzen Sie sich am besten mal mit Herrn Höttges in Verbindung.

**Comment by BechsteinJ** [comment]
Super!
Die Neuinstallation hats gebracht

Merci!
