### ISSUE TITLE
TypeError: setText

### ISSUE THREAD

**Issue by schoeller** [hoettges/QKan-plugin-HE7#3]
Dear all,

thanks for this interesting plugin. I am experiencing the following error when callling HE-import:

![image](https://user-images.githubusercontent.com/106036/64063944-00a3d200-cbeb-11e9-8628-2a108b6ddca7.png)

It seems that this is due to `setText` not being passed a string. I'll open a pull request shortly.

Best regards

Sebastian

**Comment by Invisi** [comment]
It looks like some part of the plugin wrote (most likely) `false` into the config instead of a valid file path. This shouldn't be an issue anymore once the config is validated properly in [QKan](https://www.github.com/hoettges/QKan).
